### ISSUE TITLE
How can we contribute?

### ISSUE THREAD

**Issue by mpSchrader** [pytorch/contrib#1]
Thank you for creating the repository, I think it will be very helpful to many of us. I got a few questions:

1. How will the process look like to contribute to this repository?
2. Will there be a list of ideas, which should be implemented?

Best,
Max

**Comment by apaszke** [comment]
The general idea is to be able to accept a much wider range of implementations than we could put into the core. I think we'll try to mimic the package structure of torch (e.g. `torchcontrib.optim`). The implementations will be maintained by the individual contributors, we'll only be reviewing and curating them. The releases will happen much more often than those of PyTorch (think every week or two), so you'll be able to use the latest shiny things. Eventually, if it turns out that a particular implementation is used often, we'll promote it into the core.

1. There's no special process for contributing, just the same thing as usual. It's best if you open an issue before you write any code so that we can discuss if your feature request looks ok to us, and once this happens you can submit a PR.
2. Not from our side I think. If you have any ideas please open feature requests.

**Comment by mpSchrader** [comment]
Awesome! Thank you for your answer!
